name: terraform-github-push-actions
run-name: ${{ github.actor }} running terraform apply
on: [push]
jobs:
  terraform-apply:
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Checkout the repository to the self-hosted runner
      uses: actions/checkout@v4
    - name: Echo something
      run: echo Hello world!
