name: terraform-github-push-actions
run-name: ${{ github.actor }} running terraform apply
on: [push]
jobs:
  terraform-apply:
    env:
      VAULT_ADDR: 'http://127.0.0.1:8200'
      VAULT_TOKEN: 'root'
      TF_MASHERY_VAULT_TOKEN: 'root'
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Checkout the repository to the self-hosted runner
      uses: actions/checkout@v4
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan
    - name: Terraform Apply
      run: terraform apply
      
