name: terraform-github-push-actions
run-name: ${{ github.actor }} running terraform apply
on: [push]
jobs:
  terraform-apply:
    env:
      TF_MASHERY_VAULT_TOKEN: 'root'
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Checkout the repository to the self-hosted runner
      uses: actions/checkout@v4
    - name: Terraform Init
      run: terraform init -force-copy
    - name: Terraform Plan
      run: terraform plan -destroy --out=tf.plan
    - name: Terraform Apply
      run: terraform apply -auto-approve tf.plan
      
