name: terraform-github-push-actions
run-name: ${{ github.actor }} running terraform apply
on: [push]
jobs:
  terraform:
    env:
      TF_MASHERY_VAULT_TOKEN: ${{secrets.TF_MASHERY_VAULT_TOKEN}}
    runs-on: [self-hosted, linux, x64, terraform, mashery]
    steps:
    - uses: TooMuch4U/actions-clean@v2.1
    - name: Checkout the repository to the self-hosted runner
      uses: actions/checkout@v4
    - name: Terraform Init
      run: terraform init
    - name: Terraform Create Plan
      run: terraform plan --out=tf-create.plan
    - name: Terraform Apply Create Plan
      run: terraform apply -auto-approve tf-create.plan
